# Generated by Django 4.2.7 on 2024-01-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0003_delete_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_category', models.CharField(choices=[('Python Developer', 'Python Developer'), ('Web designer', 'Web designer'), ('Graphic designer', 'Graphic designer'), ('Office Assistant', 'Office Assistant'), ('Onboarding Executive', 'Onboarding Executive')], max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.IntegerField(unique=True)),
                ('current_location', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=100)),
                ('highest_qualification', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=15)),
                ('currnet_ctc', models.CharField(max_length=15)),
                ('expected_ctc', models.CharField(max_length=15)),
                ('working_status', models.CharField(choices=[('Working', 'Working'), ('Not Working', 'Not Working')], max_length=50)),
                ('notice_period', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=30)),
                ('skill', models.CharField(max_length=50)),
                ('key_skill', models.CharField(max_length=50)),
                ('follow_status', models.CharField(choices=[('Intrested', 'Intrested'), ('Scheduled', 'Scheduled'), ('Not Intrested', 'Not Intrested'), ('Not Answer', 'Not Answer')], max_length=50)),
                ('selection_status', models.CharField(choices=[('Selected', 'Selected'), ('Not Selected', 'Not Selected')], max_length=50)),
                ('date', models.DateField()),
                ('my_file', models.FileField(blank=True, upload_to='doc')),
                ('remark', models.TextField()),
            ],
        ),
    ]
