# Generated by Django 4.2.7 on 2024-01-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='select_category',
            field=models.CharField(choices=[('Python Developer', 'Python Developer'), ('Web Designer', 'Web Designer'), ('Graphic Designer', 'Graphic Designer'), ('Office Assistant', 'Office Assistant'), ('Onboarding Executive', 'Onboarding Executive'), ('Devops', 'Devops'), ('Web Developer', 'Web Developer')], max_length=50),
        ),
    ]
