# Generated by Django 4.2.7 on 2024-01-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_resume_select_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='select_category',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skill',
        ),
        migrations.AddField(
            model_name='resume',
            name='checkbox_values',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='selected_field',
            field=models.CharField(blank=True, choices=[('Python Developer', 'Python Developer'), ('Web Designer', 'Web Designer'), ('Graphic Designer', 'Graphic Designer'), ('Office Assistant', 'Office Assistant'), ('Onboarding Executive', 'Onboarding Executive'), ('Devops', 'Devops'), ('Web Developer', 'Web Developer')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='company_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='current_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='currnet_ctc',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='expected_ctc',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='follow_status',
            field=models.CharField(blank=True, choices=[('Intrested', 'Intrested'), ('Scheduled', 'Scheduled'), ('Not Intrested', 'Not Intrested'), ('Not Answer', 'Not Answer')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='key_skill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='mobile',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='my_file',
            field=models.FileField(blank=True, null=True, upload_to='doc'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='notice_period',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='selection_status',
            field=models.CharField(blank=True, choices=[('Selected', 'Selected'), ('Not Selected', 'Not Selected')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='working_status',
            field=models.CharField(blank=True, choices=[('Working', 'Working'), ('Not Working', 'Not Working')], max_length=50, null=True),
        ),
    ]
