# Generated by Django 4.2.7 on 2024-01-22 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_resume_select_category_remove_resume_skill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='checkbox_values',
            new_name='skill',
        ),
    ]
