# Generated by Django 4.2.7 on 2024-01-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_checkbox_values_resume_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='key_skill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
