# Generated by Django 4.2.7 on 2024-01-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_resume_key_skill_alter_resume_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='key_skill',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skill',
            field=models.CharField(max_length=100),
        ),
    ]
