# Generated by Django 4.2.7 on 2024-01-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_resume_key_skill_alter_resume_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='skill',
        ),
        migrations.AddField(
            model_name='resume',
            name='checkbox_values',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
