# Generated by Django 4.2.7 on 2024-01-23 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_resume_skill_resume_checkbox_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='key_skill',
        ),
    ]
