# Generated by Django 4.2.7 on 2024-01-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_resume_key_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='key_skill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
